100%|██████████| 11/11 [00:00<00:00, 41.54it/s]
100%|██████████| 11/11 [00:00<00:00, 40.11it/s]
[2024-01-31 17:06:42,800][root][INFO] - using 1 gpus
the PU data is ['KA04', 'KA15', 'KA16', 'KA22', 'KA30', 'KB23', 'KB24', 'KB27', 'KI14', 'KI17', 'KI21']
the PU data is ['KA04', 'KA15', 'KA16', 'KA22', 'KA30', 'KB23', 'KB24', 'KB27', 'KI14', 'KI17', 'KI21']
--------PU Dataset:(1, 2) TL Task---------
the input kind is fft,the model kind is ResNet18
the opt infor is {'name': 'adamw', 'lr_src': 0.001, 'lr_tar': 0.001, 'lr_scheduler': 'designed', 'weight_decay_src': 0.0001, 'weight_decay_tar': 0.0001}
the data infor is {'data_name': 'PU', 'data_path': 'D:/P_new/PU_dataset', 'TL_list': [0, 1, 2], 'input_kind': 'fft', 'norm_kind': 'mean-std', 'TL_Task': [1, 2]}
[2024-01-31 17:06:45,861][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /api/4504800232407040/envelope/
Task: [1, 2], Iter:1/50; Accuracy_S/T = 89.31%/ 57.72%; Loss= 1.12
Task: [1, 2], Iter:2/50; Accuracy_S/T = 99.93%/ 71.83%; Loss= 0.63
[2024-01-31 17:06:57,309][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /api/4504800232407040/envelope/
Task: [1, 2], Iter:3/50; Accuracy_S/T = 96.15%/ 61.32%; Loss= 0.61
Task: [1, 2], Iter:4/50; Accuracy_S/T = 99.96%/ 78.99%; Loss= 0.59
[2024-01-31 17:07:07,768][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /api/4504800232407040/envelope/
Task: [1, 2], Iter:5/50; Accuracy_S/T = 99.93%/ 77.72%; Loss= 0.58
Task: [1, 2], Iter:6/50; Accuracy_S/T = 100.00%/ 77.57%; Loss= 0.57
Task: [1, 2], Iter:7/50; Accuracy_S/T = 100.00%/ 78.48%; Loss= 0.57
[2024-01-31 17:07:28,627][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /api/4504800232407040/envelope/
Task: [1, 2], Iter:8/50; Accuracy_S/T = 99.67%/ 77.86%; Loss= 0.57
Task: [1, 2], Iter:9/50; Accuracy_S/T = 100.00%/ 78.12%; Loss= 0.56
[2024-01-31 17:07:39,053][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /api/4504800232407040/envelope/
Task: [1, 2], Iter:10/50; Accuracy_S/T = 100.00%/ 73.76%; Loss= 0.56
Task: [1, 2], Iter:11/50; Accuracy_S/T = 100.00%/ 78.88%; Loss= 0.56
[2024-01-31 17:07:49,484][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /api/4504800232407040/envelope/
Task: [1, 2], Iter:12/50; Accuracy_S/T = 100.00%/ 75.97%; Loss= 0.56
Task: [1, 2], Iter:13/50; Accuracy_S/T = 100.00%/ 73.06%; Loss= 0.56
Task: [1, 2], Iter:14/50; Accuracy_S/T = 100.00%/ 74.30%; Loss= 0.56
Task: [1, 2], Iter:15/50; Accuracy_S/T = 100.00%/ 75.97%; Loss= 0.56
Task: [1, 2], Iter:16/50; Accuracy_S/T = 100.00%/ 71.68%; Loss= 0.56
Task: [1, 2], Iter:17/50; Accuracy_S/T = 100.00%/ 75.68%; Loss= 0.56
Task: [1, 2], Iter:18/50; Accuracy_S/T = 100.00%/ 79.43%; Loss= 0.55
Task: [1, 2], Iter:19/50; Accuracy_S/T = 100.00%/ 75.21%; Loss= 0.56
Task: [1, 2], Iter:20/50; Accuracy_S/T = 100.00%/ 75.86%; Loss= 0.56
Task: [1, 2], Iter:21/50; Accuracy_S/T = 100.00%/ 74.63%; Loss= 0.55
Task: [1, 2], Iter:22/50; Accuracy_S/T = 100.00%/ 77.21%; Loss= 0.56
Task: [1, 2], Iter:23/50; Accuracy_S/T = 100.00%/ 78.26%; Loss= 0.55
Task: [1, 2], Iter:24/50; Accuracy_S/T = 100.00%/ 74.55%; Loss= 0.55
Task: [1, 2], Iter:25/50; Accuracy_S/T = 100.00%/ 76.95%; Loss= 0.55
Task: [1, 2], Iter:26/50; Accuracy_S/T = 100.00%/ 77.03%; Loss= 0.55
Task: [1, 2], Iter:27/50; Accuracy_S/T = 100.00%/ 74.88%; Loss= 0.55
Task: [1, 2], Iter:28/50; Accuracy_S/T = 100.00%/ 75.14%; Loss= 0.55
Task: [1, 2], Iter:29/50; Accuracy_S/T = 100.00%/ 76.74%; Loss= 0.55
Task: [1, 2], Iter:30/50; Accuracy_S/T = 100.00%/ 75.06%; Loss= 0.55
Task: [1, 2], Iter:31/50; Accuracy_S/T = 100.00%/ 75.72%; Loss= 0.55
Task: [1, 2], Iter:32/50; Accuracy_S/T = 100.00%/ 76.08%; Loss= 0.55
Task: [1, 2], Iter:33/50; Accuracy_S/T = 100.00%/ 75.65%; Loss= 0.55
Task: [1, 2], Iter:34/50; Accuracy_S/T = 100.00%/ 76.34%; Loss= 0.55
Task: [1, 2], Iter:35/50; Accuracy_S/T = 100.00%/ 75.14%; Loss= 0.55
Task: [1, 2], Iter:36/50; Accuracy_S/T = 100.00%/ 76.44%; Loss= 0.55
Task: [1, 2], Iter:37/50; Accuracy_S/T = 100.00%/ 75.83%; Loss= 0.55
Task: [1, 2], Iter:38/50; Accuracy_S/T = 100.00%/ 77.28%; Loss= 0.55
Task: [1, 2], Iter:39/50; Accuracy_S/T = 100.00%/ 74.88%; Loss= 0.55
Task: [1, 2], Iter:40/50; Accuracy_S/T = 100.00%/ 76.30%; Loss= 0.55
Task: [1, 2], Iter:41/50; Accuracy_S/T = 100.00%/ 76.41%; Loss= 0.55
Task: [1, 2], Iter:42/50; Accuracy_S/T = 100.00%/ 73.90%; Loss= 0.55
Task: [1, 2], Iter:43/50; Accuracy_S/T = 100.00%/ 74.05%; Loss= 0.55
Task: [1, 2], Iter:44/50; Accuracy_S/T = 100.00%/ 75.94%; Loss= 0.55
Task: [1, 2], Iter:45/50; Accuracy_S/T = 100.00%/ 75.28%; Loss= 0.55
Task: [1, 2], Iter:46/50; Accuracy_S/T = 100.00%/ 76.19%; Loss= 0.55
Task: [1, 2], Iter:47/50; Accuracy_S/T = 100.00%/ 75.57%; Loss= 0.55
Task: [1, 2], Iter:48/50; Accuracy_S/T = 100.00%/ 74.59%; Loss= 0.55
Task: [1, 2], Iter:49/50; Accuracy_S/T = 100.00%/ 74.74%; Loss= 0.55
Task: [1, 2], Iter:50/50; Accuracy_S/T = 100.00%/ 76.70%; Loss= 0.55