2024-01-31 16:31:45,947 INFO    StreamThr :25144 [internal.py:wandb_internal():86] W&B internal server running at pid: 25144, started at: 2024-01-31 16:31:45.946715
2024-01-31 16:31:45,949 DEBUG   HandlerThread:25144 [handler.py:handle_request():146] handle_request: status
2024-01-31 16:31:45,960 INFO    WriterThread:25144 [datastore.py:open_for_write():85] open: D:\Source_Code_Work\TTA_MFD\wandb\run-20240131_163145-mos4mrc0\run-mos4mrc0.wandb
2024-01-31 16:31:45,961 DEBUG   SenderThread:25144 [sender.py:send():380] send: header
2024-01-31 16:31:45,964 DEBUG   SenderThread:25144 [sender.py:send():380] send: run
2024-01-31 16:31:46,972 INFO    WriterThread:25144 [datastore.py:close():294] close: D:\Source_Code_Work\TTA_MFD\wandb\run-20240131_163145-mos4mrc0\run-mos4mrc0.wandb
2024-01-31 16:31:46,972 INFO    HandlerThread:25144 [handler.py:finish():866] shutting down handler
2024-01-31 16:31:46,973 ERROR   StreamThr :25144 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "D:\P\anaconda\envs\pytorch\lib\site-packages\wandb\sdk\internal\internal_util.py", line 49, in run
    self._run()
  File "D:\P\anaconda\envs\pytorch\lib\site-packages\wandb\sdk\internal\internal_util.py", line 100, in _run
    self._process(record)
  File "D:\P\anaconda\envs\pytorch\lib\site-packages\wandb\sdk\internal\internal.py", line 328, in _process
    self._sm.send(record)
  File "D:\P\anaconda\envs\pytorch\lib\site-packages\wandb\sdk\internal\sender.py", line 387, in send
    send_handler(record)
  File "D:\P\anaconda\envs\pytorch\lib\site-packages\wandb\sdk\internal\sender.py", line 939, in send_run
    self._config_save(config_value_dict)
  File "D:\P\anaconda\envs\pytorch\lib\site-packages\wandb\sdk\internal\sender.py", line 897, in _config_save
    config_util.save_config_file_from_dict(config_path, config_value_dict)
  File "D:\P\anaconda\envs\pytorch\lib\site-packages\wandb\sdk\lib\config_util.py", line 92, in save_config_file_from_dict
    conf_file.write(data)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2029' in position 1145: illegal multibyte sequence
